server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ems
    username: ems_user
    password: ems_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
